# Form implementation generated from reading ui file 'D:\HUFLIT\Nam3\BMHTTT\DoAN\View\ThietKe\loginDialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(831, 581)
        Dialog.setStyleSheet("#Dialog{\n"
"background-color: #292C35;\n"
"}\n"
"")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 401, 601))
        self.label_4.setStyleSheet("background-image: url(D:/HUFLIT/Nam3/BMHTTT/DoAn/View/icon/bmdn3.jpg);\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(470, 440, 320, 38))
        self.cancelButton.setStyleSheet("\n"
"\n"
"color: #1074CA;\n"
"border-radius: 10px;\n"
"border: 2px solid #1074CA;\n"
"\n"
"\n"
"border-radius: 10px;\n"
"font: 12pt \"Times New Roman\";\n"
"\n"
"")
        self.cancelButton.setObjectName("cancelButton")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(470, 220, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.usernameInput = QtWidgets.QLineEdit(parent=Dialog)
        self.usernameInput.setGeometry(QtCore.QRect(480, 160, 311, 51))
        self.usernameInput.setStyleSheet("QLineEdit {\n"
"padding-left:60px;\n"
"border-radius: 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 10pt \"Times New Roman\";\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.usernameInput.setObjectName("usernameInput")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(540, 60, 251, 51))
        self.label.setMaximumSize(QtCore.QSize(16777212, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.passwordInput = QtWidgets.QLineEdit(parent=Dialog)
        self.passwordInput.setGeometry(QtCore.QRect(480, 250, 311, 51))
        self.passwordInput.setStyleSheet("QLineEdit {\n"
"padding-left:60px;\n"
"border-radius: 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 10pt \"Times New Roman\";\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.passwordInput.setInputMask("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.loginButton = QtWidgets.QPushButton(parent=Dialog)
        self.loginButton.setGeometry(QtCore.QRect(470, 330, 320, 40))
        self.loginButton.setStyleSheet("\n"
"background-color: #1074CA;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"font: 12pt \"Times New Roman\";\n"
"\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.showPasswordButton = QtWidgets.QPushButton(parent=Dialog)
        self.showPasswordButton.setGeometry(QtCore.QRect(740, 260, 40, 40))
        self.showPasswordButton.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.showPasswordButton.setStyleSheet("border-radius:1px;")
        self.showPasswordButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/HUFLIT/Nam3/BMHTTT/DoAn/View/icon/eyes_1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.showPasswordButton.setIcon(icon)
        self.showPasswordButton.setIconSize(QtCore.QSize(30, 30))
        self.showPasswordButton.setObjectName("showPasswordButton")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(470, 130, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        self.label_7.setGeometry(QtCore.QRect(470, 160, 51, 51))
        self.label_7.setStyleSheet("\n"
"background-color: #1074CA;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=Dialog)
        self.label_8.setGeometry(QtCore.QRect(480, 170, 30, 30))
        self.label_8.setStyleSheet("image: url(D:/HUFLIT/Nam3/BMHTTT/DoAn/View/icon/user.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=Dialog)
        self.label_9.setGeometry(QtCore.QRect(470, 250, 51, 51))
        self.label_9.setStyleSheet("\n"
"background-color: #1074CA;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=Dialog)
        self.label_10.setGeometry(QtCore.QRect(480, 260, 30, 30))
        self.label_10.setStyleSheet("\n"
"image: url(D:/HUFLIT/Nam3/BMHTTT/DoAn/View/icon/Khoa.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(610, 400, 55, 21))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 13pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(470, 400, 121, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=Dialog)
        self.line_2.setGeometry(QtCore.QRect(670, 400, 121, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancelButton.setText(_translate("Dialog", "Thoát"))
        self.label_3.setText(_translate("Dialog", "Mật khẩu"))
        self.usernameInput.setPlaceholderText(_translate("Dialog", "Nhập tên tài khoản"))
        self.label.setText(_translate("Dialog", "ĐĂNG NHẬP"))
        self.passwordInput.setPlaceholderText(_translate("Dialog", "Nhập mật khẩu"))
        self.loginButton.setText(_translate("Dialog", "Đăng nhập"))
        self.label_2.setText(_translate("Dialog", "Tên tài khoản"))
        self.label_5.setText(_translate("Dialog", "Hoặc"))
