# Form implementation generated from reading ui file 'D:\HUFLIT\Nam3\BMHTTT\DoAn\View\ThietKe\ThietKeSlideBarMenu.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OtherWindow(object):
    def setupUi(self, OtherWindow):
        OtherWindow.setObjectName("OtherWindow")
        OtherWindow.resize(1087, 627)
        OtherWindow.setStyleSheet("background-color: #292C35;")
        self.centralwidget = QtWidgets.QWidget(parent=OtherWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.menu_widget.setGeometry(QtCore.QRect(10, 20, 201, 581))
        self.menu_widget.setStyleSheet("background-color: #21252A;\n"
"color: #fff;\n"
"border: none;\n"
"font: 12pt \"Times New Roman\";")
        self.menu_widget.setObjectName("menu_widget")
        self.toolBox = QtWidgets.QToolBox(parent=self.menu_widget)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 211, 581))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("#toolBox {\n"
"    color: #fff;\n"
"}\n"
"#Mahoatoolbox {\n"
"    color:  #fff;\n"
"}\n"
"#Mahoatoolbox::tab {\n"
"    padding-left:5px;\n"
"    text-align:left;\n"
"    border-radius: 2px;\n"
"}\n"
"#Mahoatoolbox::tab:selected {\n"
"    background-color: #6171A4;\n"
"    font-weight: bold;\n"
"}\n"
"#Giaimatoolbox::tab {\n"
"    padding-left:5px;\n"
"    text-align:left;\n"
"    border-radius: 2px;\n"
"}\n"
"#Giaimatoolbox::tab:selected {\n"
"    background-color: #6171A4;\n"
"    font-weight: bold;\n"
"}\n"
"#toolBox::tab {\n"
"    padding-left:5px;\n"
"    text-align:left;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"\n"
"#toolBox::tab:selected {\n"
"    background-color: #3B3D60;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#toolBox QPushButton {\n"
"    padding:5px 0px 5px 20px;\n"
"    text-align:left;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#toolBox QPushButton:hover {\n"
"    background-color: #FC7CC0;\n"
"}\n"
"\n"
"\n"
"#toolBox QPushButton:checked {\n"
"    background-color: #FC7CC0;\n"
"}\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 211, 507))
        self.page_3.setObjectName("page_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Mahoatoolbox = QtWidgets.QToolBox(parent=self.page_3)
        self.Mahoatoolbox.setObjectName("Mahoatoolbox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 189, 300))
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.actionCeasar_MaHoa = QtWidgets.QPushButton(parent=self.page)
        self.actionCeasar_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.actionCeasar_MaHoa.setCheckable(False)
        self.actionCeasar_MaHoa.setObjectName("actionCeasar_MaHoa")
        self.verticalLayout_5.addWidget(self.actionCeasar_MaHoa)
        self.actionVignere_MaHoa = QtWidgets.QPushButton(parent=self.page)
        self.actionVignere_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionVignere_MaHoa.setCheckable(False)
        self.actionVignere_MaHoa.setObjectName("actionVignere_MaHoa")
        self.verticalLayout_5.addWidget(self.actionVignere_MaHoa)
        self.actionTrithemius_MaHoa = QtWidgets.QPushButton(parent=self.page)
        self.actionTrithemius_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionTrithemius_MaHoa.setCheckable(False)
        self.actionTrithemius_MaHoa.setObjectName("actionTrithemius_MaHoa")
        self.verticalLayout_5.addWidget(self.actionTrithemius_MaHoa)
        self.actionBelasco_MaHoa = QtWidgets.QPushButton(parent=self.page)
        self.actionBelasco_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionBelasco_MaHoa.setCheckable(False)
        self.actionBelasco_MaHoa.setObjectName("actionBelasco_MaHoa")
        self.verticalLayout_5.addWidget(self.actionBelasco_MaHoa)
        spacerItem = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.Mahoatoolbox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 189, 300))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.actionHai_dong_MaHoa = QtWidgets.QPushButton(parent=self.page_2)
        self.actionHai_dong_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionHai_dong_MaHoa.setCheckable(False)
        self.actionHai_dong_MaHoa.setObjectName("actionHai_dong_MaHoa")
        self.verticalLayout_6.addWidget(self.actionHai_dong_MaHoa)
        self.actionNhieu_dong_MaHoa = QtWidgets.QPushButton(parent=self.page_2)
        self.actionNhieu_dong_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionNhieu_dong_MaHoa.setCheckable(False)
        self.actionNhieu_dong_MaHoa.setObjectName("actionNhieu_dong_MaHoa")
        self.verticalLayout_6.addWidget(self.actionNhieu_dong_MaHoa)
        spacerItem1 = QtWidgets.QSpacerItem(20, 214, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.Mahoatoolbox.addItem(self.page_2, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 189, 300))
        self.page_7.setObjectName("page_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.actionCeasar_XOR_MaHoa = QtWidgets.QPushButton(parent=self.page_7)
        self.actionCeasar_XOR_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.actionCeasar_XOR_MaHoa.setCheckable(False)
        self.actionCeasar_XOR_MaHoa.setObjectName("actionCeasar_XOR_MaHoa")
        self.verticalLayout_7.addWidget(self.actionCeasar_XOR_MaHoa)
        self.actionVignere_XOR_MaHoa = QtWidgets.QPushButton(parent=self.page_7)
        self.actionVignere_XOR_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionVignere_XOR_MaHoa.setCheckable(False)
        self.actionVignere_XOR_MaHoa.setObjectName("actionVignere_XOR_MaHoa")
        self.verticalLayout_7.addWidget(self.actionVignere_XOR_MaHoa)
        self.actionTrithemius_XOR_MaHoa = QtWidgets.QPushButton(parent=self.page_7)
        self.actionTrithemius_XOR_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionTrithemius_XOR_MaHoa.setCheckable(False)
        self.actionTrithemius_XOR_MaHoa.setObjectName("actionTrithemius_XOR_MaHoa")
        self.verticalLayout_7.addWidget(self.actionTrithemius_XOR_MaHoa)
        self.actionBelasco_XOR_MaHoa = QtWidgets.QPushButton(parent=self.page_7)
        self.actionBelasco_XOR_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionBelasco_XOR_MaHoa.setCheckable(False)
        self.actionBelasco_XOR_MaHoa.setObjectName("actionBelasco_XOR_MaHoa")
        self.verticalLayout_7.addWidget(self.actionBelasco_XOR_MaHoa)
        spacerItem2 = QtWidgets.QSpacerItem(20, 136, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.Mahoatoolbox.addItem(self.page_7, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 189, 300))
        self.page_8.setObjectName("page_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.actionSDES_MaHoa = QtWidgets.QPushButton(parent=self.page_8)
        self.actionSDES_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionSDES_MaHoa.setCheckable(False)
        self.actionSDES_MaHoa.setObjectName("actionSDES_MaHoa")
        self.verticalLayout_8.addWidget(self.actionSDES_MaHoa)
        self.actionRSA_MaHoa = QtWidgets.QPushButton(parent=self.page_8)
        self.actionRSA_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionRSA_MaHoa.setCheckable(False)
        self.actionRSA_MaHoa.setObjectName("actionRSA_MaHoa")
        self.verticalLayout_8.addWidget(self.actionRSA_MaHoa)
        self.actionAES_MaHoa = QtWidgets.QPushButton(parent=self.page_8)
        self.actionAES_MaHoa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionAES_MaHoa.setCheckable(False)
        self.actionAES_MaHoa.setObjectName("actionAES_MaHoa")
        self.verticalLayout_8.addWidget(self.actionAES_MaHoa)
        spacerItem3 = QtWidgets.QSpacerItem(20, 175, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.Mahoatoolbox.addItem(self.page_8, "")
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setGeometry(QtCore.QRect(0, 0, 189, 300))
        self.page_13.setObjectName("page_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_13)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.actionMD5_MaHoa = QtWidgets.QPushButton(parent=self.page_13)
        self.actionMD5_MaHoa.setObjectName("actionMD5_MaHoa")
        self.verticalLayout_11.addWidget(self.actionMD5_MaHoa)
        self.actionSHA3_MaHoa = QtWidgets.QPushButton(parent=self.page_13)
        self.actionSHA3_MaHoa.setObjectName("actionSHA3_MaHoa")
        self.verticalLayout_11.addWidget(self.actionSHA3_MaHoa)
        self.actionSHA256_MaHoa = QtWidgets.QPushButton(parent=self.page_13)
        self.actionSHA256_MaHoa.setObjectName("actionSHA256_MaHoa")
        self.verticalLayout_11.addWidget(self.actionSHA256_MaHoa)
        spacerItem4 = QtWidgets.QSpacerItem(20, 158, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem4)
        self.Mahoatoolbox.addItem(self.page_13, "")
        self.verticalLayout.addWidget(self.Mahoatoolbox)
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 211, 507))
        self.page_4.setObjectName("page_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Giaimatoolbox = QtWidgets.QToolBox(parent=self.page_4)
        self.Giaimatoolbox.setObjectName("Giaimatoolbox")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 167, 178))
        self.page_5.setObjectName("page_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.actionCeasar_GiaiMa = QtWidgets.QPushButton(parent=self.page_5)
        self.actionCeasar_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.actionCeasar_GiaiMa.setCheckable(False)
        self.actionCeasar_GiaiMa.setObjectName("actionCeasar_GiaiMa")
        self.verticalLayout_3.addWidget(self.actionCeasar_GiaiMa)
        self.actionVignere_GiaiMa = QtWidgets.QPushButton(parent=self.page_5)
        self.actionVignere_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionVignere_GiaiMa.setCheckable(False)
        self.actionVignere_GiaiMa.setObjectName("actionVignere_GiaiMa")
        self.verticalLayout_3.addWidget(self.actionVignere_GiaiMa)
        self.actionTrithemius_GiaiMa = QtWidgets.QPushButton(parent=self.page_5)
        self.actionTrithemius_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionTrithemius_GiaiMa.setCheckable(False)
        self.actionTrithemius_GiaiMa.setObjectName("actionTrithemius_GiaiMa")
        self.verticalLayout_3.addWidget(self.actionTrithemius_GiaiMa)
        self.actionBelasco_GiaiMa = QtWidgets.QPushButton(parent=self.page_5)
        self.actionBelasco_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionBelasco_GiaiMa.setCheckable(False)
        self.actionBelasco_GiaiMa.setObjectName("actionBelasco_GiaiMa")
        self.verticalLayout_3.addWidget(self.actionBelasco_GiaiMa)
        spacerItem5 = QtWidgets.QSpacerItem(20, 136, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.Giaimatoolbox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 173, 100))
        self.page_6.setObjectName("page_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.actionHai_dong_GiaiMa = QtWidgets.QPushButton(parent=self.page_6)
        self.actionHai_dong_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionHai_dong_GiaiMa.setCheckable(False)
        self.actionHai_dong_GiaiMa.setObjectName("actionHai_dong_GiaiMa")
        self.verticalLayout_4.addWidget(self.actionHai_dong_GiaiMa)
        self.actionNhieu_dong_GiaiMa = QtWidgets.QPushButton(parent=self.page_6)
        self.actionNhieu_dong_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionNhieu_dong_GiaiMa.setCheckable(False)
        self.actionNhieu_dong_GiaiMa.setObjectName("actionNhieu_dong_GiaiMa")
        self.verticalLayout_4.addWidget(self.actionNhieu_dong_GiaiMa)
        spacerItem6 = QtWidgets.QSpacerItem(20, 251, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.Giaimatoolbox.addItem(self.page_6, "")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 218, 178))
        self.page_9.setObjectName("page_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.actionCeasar_XOR_GiaiMa = QtWidgets.QPushButton(parent=self.page_9)
        self.actionCeasar_XOR_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.actionCeasar_XOR_GiaiMa.setCheckable(False)
        self.actionCeasar_XOR_GiaiMa.setObjectName("actionCeasar_XOR_GiaiMa")
        self.verticalLayout_9.addWidget(self.actionCeasar_XOR_GiaiMa)
        self.actionVignere_XOR_GiaiMa = QtWidgets.QPushButton(parent=self.page_9)
        self.actionVignere_XOR_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionVignere_XOR_GiaiMa.setCheckable(False)
        self.actionVignere_XOR_GiaiMa.setObjectName("actionVignere_XOR_GiaiMa")
        self.verticalLayout_9.addWidget(self.actionVignere_XOR_GiaiMa)
        self.actionTrithemius_XOR_GiaiMa = QtWidgets.QPushButton(parent=self.page_9)
        self.actionTrithemius_XOR_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionTrithemius_XOR_GiaiMa.setCheckable(False)
        self.actionTrithemius_XOR_GiaiMa.setObjectName("actionTrithemius_XOR_GiaiMa")
        self.verticalLayout_9.addWidget(self.actionTrithemius_XOR_GiaiMa)
        self.actionBelasco_XOR_GiaiMa = QtWidgets.QPushButton(parent=self.page_9)
        self.actionBelasco_XOR_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionBelasco_XOR_GiaiMa.setCheckable(False)
        self.actionBelasco_XOR_GiaiMa.setObjectName("actionBelasco_XOR_GiaiMa")
        self.verticalLayout_9.addWidget(self.actionBelasco_XOR_GiaiMa)
        spacerItem7 = QtWidgets.QSpacerItem(20, 136, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.Giaimatoolbox.addItem(self.page_9, "")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 189, 337))
        self.page_10.setObjectName("page_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.actionSDES_GiaiMa = QtWidgets.QPushButton(parent=self.page_10)
        self.actionSDES_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionSDES_GiaiMa.setCheckable(False)
        self.actionSDES_GiaiMa.setObjectName("actionSDES_GiaiMa")
        self.verticalLayout_10.addWidget(self.actionSDES_GiaiMa)
        self.actionRSA_GiaiMa = QtWidgets.QPushButton(parent=self.page_10)
        self.actionRSA_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionRSA_GiaiMa.setCheckable(False)
        self.actionRSA_GiaiMa.setObjectName("actionRSA_GiaiMa")
        self.verticalLayout_10.addWidget(self.actionRSA_GiaiMa)
        self.actionAES_GiaiMa = QtWidgets.QPushButton(parent=self.page_10)
        self.actionAES_GiaiMa.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.actionAES_GiaiMa.setCheckable(False)
        self.actionAES_GiaiMa.setObjectName("actionAES_GiaiMa")
        self.verticalLayout_10.addWidget(self.actionAES_GiaiMa)
        spacerItem8 = QtWidgets.QSpacerItem(20, 175, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem8)
        self.Giaimatoolbox.addItem(self.page_10, "")
        self.verticalLayout_2.addWidget(self.Giaimatoolbox)
        self.toolBox.addItem(self.page_4, "")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(240, 20, 831, 581))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("#tabWidget {\n"
"    background-color: #292C35;\n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"    margin-left: 3px;\n"
"    image: url(D:/HUFLIT/Nam3/BMHTTT/DoAn/View/icon/thoat_menu.png);\n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    margin-left: 3px;    \n"
"    image: url(D:/HUFLIT/Nam3/BMHTTT/DoAn/View/icon/thoat_menu_1.png);\n"
"}\n"
"\n"
"")
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        OtherWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=OtherWindow)
        self.statusbar.setObjectName("statusbar")
        OtherWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OtherWindow)
        self.toolBox.setCurrentIndex(0)
        self.Mahoatoolbox.setCurrentIndex(0)
        self.Giaimatoolbox.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow)

    def retranslateUi(self, OtherWindow):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow.setWindowTitle(_translate("OtherWindow", "MainWindow"))
        self.toolBox.setWhatsThis(_translate("OtherWindow", "#toolBox{\n"
"    color: #fff;\n"
"}\n"
"#"))
        self.actionCeasar_MaHoa.setText(_translate("OtherWindow", "Caesar"))
        self.actionVignere_MaHoa.setText(_translate("OtherWindow", "Vignere"))
        self.actionTrithemius_MaHoa.setText(_translate("OtherWindow", "Trithemius"))
        self.actionBelasco_MaHoa.setText(_translate("OtherWindow", "Belasco"))
        self.Mahoatoolbox.setItemText(self.Mahoatoolbox.indexOf(self.page), _translate("OtherWindow", "Kỹ thuật thay thế"))
        self.actionHai_dong_MaHoa.setText(_translate("OtherWindow", "Hai dòng"))
        self.actionNhieu_dong_MaHoa.setText(_translate("OtherWindow", "Nhiều dòng"))
        self.Mahoatoolbox.setItemText(self.Mahoatoolbox.indexOf(self.page_2), _translate("OtherWindow", "Kỹ thuật chuyển vị "))
        self.actionCeasar_XOR_MaHoa.setText(_translate("OtherWindow", "Caesar_XOR"))
        self.actionVignere_XOR_MaHoa.setText(_translate("OtherWindow", "Vignere_XOR"))
        self.actionTrithemius_XOR_MaHoa.setText(_translate("OtherWindow", "Trithemius_XOR"))
        self.actionBelasco_XOR_MaHoa.setText(_translate("OtherWindow", "Belasco_XOR"))
        self.Mahoatoolbox.setItemText(self.Mahoatoolbox.indexOf(self.page_7), _translate("OtherWindow", "Kỹ thuật XOR "))
        self.actionSDES_MaHoa.setText(_translate("OtherWindow", "SDES"))
        self.actionRSA_MaHoa.setText(_translate("OtherWindow", "RSA"))
        self.actionAES_MaHoa.setText(_translate("OtherWindow", "AES"))
        self.Mahoatoolbox.setItemText(self.Mahoatoolbox.indexOf(self.page_8), _translate("OtherWindow", "Hiện đại "))
        self.actionMD5_MaHoa.setText(_translate("OtherWindow", "MD5"))
        self.actionSHA3_MaHoa.setText(_translate("OtherWindow", "SHA3"))
        self.actionSHA256_MaHoa.setText(_translate("OtherWindow", "SHA256"))
        self.Mahoatoolbox.setItemText(self.Mahoatoolbox.indexOf(self.page_13), _translate("OtherWindow", "Một chiều"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("OtherWindow", "Mã hóa"))
        self.actionCeasar_GiaiMa.setText(_translate("OtherWindow", "Caesar_GM"))
        self.actionVignere_GiaiMa.setText(_translate("OtherWindow", "Vignere_GM"))
        self.actionTrithemius_GiaiMa.setText(_translate("OtherWindow", "Trithemius_GM"))
        self.actionBelasco_GiaiMa.setText(_translate("OtherWindow", "Belasco_GM"))
        self.Giaimatoolbox.setItemText(self.Giaimatoolbox.indexOf(self.page_5), _translate("OtherWindow", "Kỹ thuật thay thế "))
        self.actionHai_dong_GiaiMa.setText(_translate("OtherWindow", "Hai dòng_GM"))
        self.actionNhieu_dong_GiaiMa.setText(_translate("OtherWindow", "Nhiều dòng_GM"))
        self.Giaimatoolbox.setItemText(self.Giaimatoolbox.indexOf(self.page_6), _translate("OtherWindow", "Kỹ thuật chuyển vị "))
        self.actionCeasar_XOR_GiaiMa.setText(_translate("OtherWindow", "Caesar_XOR_GM"))
        self.actionVignere_XOR_GiaiMa.setText(_translate("OtherWindow", "Vignere_XOR_GM"))
        self.actionTrithemius_XOR_GiaiMa.setText(_translate("OtherWindow", "Trithemius_XOR_GM"))
        self.actionBelasco_XOR_GiaiMa.setText(_translate("OtherWindow", "Belasco_XOR_GM"))
        self.Giaimatoolbox.setItemText(self.Giaimatoolbox.indexOf(self.page_9), _translate("OtherWindow", "Kỹ thuật XOR"))
        self.actionSDES_GiaiMa.setText(_translate("OtherWindow", "SDES_GM"))
        self.actionRSA_GiaiMa.setText(_translate("OtherWindow", "RSA_GM"))
        self.actionAES_GiaiMa.setText(_translate("OtherWindow", "AES_GM"))
        self.Giaimatoolbox.setItemText(self.Giaimatoolbox.indexOf(self.page_10), _translate("OtherWindow", "Hiện đại"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("OtherWindow", "Giải mã "))
